import {
  ImportEntityType,
  EntityConfig,
} from "@/types/bulkImport";

export const ENTITY_CONFIGS: Record<ImportEntityType, EntityConfig> = {
  doctors: {
    type: "doctors",
    titleBn: "বিশেষজ্ঞ ডাক্তার",
    titleEn: "Specialist Doctors",
    descBn: "ডাক্তারদের তথ্য, স্পেশালিটি, চেম্বার, ভিজিটিং সময় ও সিরিয়াল নম্বর",
    descEn: "Doctor profiles, specialties, chamber locations, visiting hours & phone",
    columns: [
      {
        key: "name",
        labelBn: "ডাক্তারের নাম",
        labelEn: "Doctor Name",
        required: true,
        aliases: ["name", "doctor_name", "doctor name", "নাম", "ডাক্তারের নাম", "dr_name", "dr name"],
        exampleValue: "ডাঃ মোঃ রফিকুল ইসলাম",
      },
      {
        key: "specialty",
        labelBn: "স্পেশালিটি / রোগ বিশেষজ্ঞ",
        labelEn: "Specialty",
        required: true,
        aliases: ["specialty", "specialist", "স্পেশালিটি", "রোগ বিশেষজ্ঞ", "বিশেষজ্ঞ"],
        exampleValue: "মেডিসিন ও বক্ষব্যাধি বিশেষজ্ঞ",
      },
      {
        key: "department",
        labelBn: "ডিপার্টমেন্ট",
        labelEn: "Department",
        required: true,
        aliases: ["department", "dept", "বিভাগ", "ডিপার্টমেন্ট", "শাখা"],
        exampleValue: "medicine",
      },
      {
        key: "degrees",
        labelBn: "ডিগ্রিসমূহ",
        labelEn: "Degrees / Qualifications",
        required: true,
        aliases: ["degrees", "degree", "qualification", "ডিগ্রি", "শিক্ষাগত যোগ্যতা"],
        exampleValue: "MBBS, FCPS (Medicine), MACP (USA)",
      },
      {
        key: "designation",
        labelBn: "পদবী / হাসপাতাল",
        labelEn: "Designation",
        required: true,
        aliases: ["designation", "title", "পদবী", "বর্তমান পদবী", "কর্মস্থল"],
        exampleValue: "সহকারী অধ্যাপক, মেডিসিন বিভাগ",
      },
      {
        key: "chamberName",
        labelBn: "চেম্বারের নাম",
        labelEn: "Chamber Name",
        required: true,
        aliases: ["chambername", "chamber_name", "chamber", "hospital", "চেম্বার", "চেম্বারের নাম", "হাসপাতাল"],
        exampleValue: "ল্যাবএইড স্পেশালাইজড ডায়াগনস্টিক",
      },
      {
        key: "chamberAddress",
        labelBn: "চেম্বারের ঠিকানা",
        labelEn: "Chamber Address",
        required: true,
        aliases: ["chamberaddress", "chamber_address", "address", "ঠিকানা", "চেম্বারের ঠিকানা"],
        exampleValue: "এসএসকে রোড, ট্রাঙ্ক রোড মোড়, ফেনী",
      },
      {
        key: "roomNo",
        labelBn: "রুম নম্বর",
        labelEn: "Room No",
        required: false,
        aliases: ["roomno", "room_no", "room", "রুম নং", "রুম নম্বর"],
        exampleValue: "৩০২ (৩য় তলা)",
      },
      {
        key: "visitingDays",
        labelBn: "রোগী দেখার দিন",
        labelEn: "Visiting Days",
        required: true,
        aliases: ["visitingdays", "visiting_days", "days", "দিন", "রোগী দেখার দিন"],
        exampleValue: "শনি থেকে বৃহস্পতি",
      },
      {
        key: "visitingHours",
        labelBn: "রোগী দেখার সময়",
        labelEn: "Visiting Hours",
        required: true,
        aliases: ["visitinghours", "visiting_hours", "hours", "time", "সময়", "রোগী দেখার সময়"],
        exampleValue: "বিকাল ৫টা - রাত ৯টা",
      },
      {
        key: "serialPhone",
        labelBn: "সিরিয়াল ফোন",
        labelEn: "Serial Phone",
        required: true,
        aliases: ["serialphone", "serial_phone", "phone", "mobile", "মোবাইল", "ফোন", "সিরিয়াল ফোন"],
        exampleValue: "01711223344",
      },
      {
        key: "consultationFee",
        labelBn: "পরামর্শ ফি",
        labelEn: "Consultation Fee",
        required: false,
        aliases: ["consultationfee", "consultation_fee", "fee", "ভিজিট", "ফি", "পরামর্শ ফি"],
        exampleValue: "৮০০ টাকা (নতুন), ৫০০ টাকা (পুরাতন)",
      },
      {
        key: "upazila",
        labelBn: "উপজেলা / এলাকা",
        labelEn: "Upazila / Area",
        required: false,
        aliases: ["upazila", "area", "উপজেলা", "এলাকা", "থানা"],
        exampleValue: "feni-sadar",
      },
    ],
  },
  partners: {
    type: "partners",
    titleBn: "পার্টনার নেটওয়ার্ক (হাসপাতাল/ল্যাব/ফার্মেসি)",
    titleEn: "Partner Network (Hospitals/Labs/Pharmacies)",
    descBn: "চুক্তিভিত্তিক হাসপাতাল, ডায়াগনস্টিক ও ফার্মেসির নাম, ছাড় ও যোগাযোগ",
    descEn: "Partner hospitals, diagnostics and pharmacies with discounts and contact info",
    columns: [
      {
        key: "name",
        labelBn: "প্রতিষ্ঠানের নাম",
        labelEn: "Facility Name",
        required: true,
        aliases: ["name", "partner_name", "hospital_name", "নাম", "প্রতিষ্ঠানের নাম"],
        exampleValue: "পপুলার ডায়াগনস্টিক সেন্টার",
      },
      {
        key: "category",
        labelBn: "ক্যাটাগরি",
        labelEn: "Category (hospital/diagnostic/pharmacy)",
        required: true,
        aliases: ["category", "type", "ক্যাটাগরি", "ধরণ"],
        exampleValue: "diagnostic",
      },
      {
        key: "address",
        labelBn: "ঠিকানা",
        labelEn: "Address",
        required: true,
        aliases: ["address", "location", "ঠিকানা", "লোকেশন"],
        exampleValue: "এসএসকে রোড, ফেনী সদর, ফেনী",
      },
      {
        key: "discount",
        labelBn: "ডিসকাউন্ট বিবরণ",
        labelEn: "Discount Description",
        required: true,
        aliases: ["discount", "discount_rate", "ছাড়", "ডিসকাউন্ট", "ডিসকাউন্ট রেট"],
        exampleValue: "১০-৩০% ডিসকাউন্ট",
      },
      {
        key: "phone",
        labelBn: "ফোন / হেল্পলাইন",
        labelEn: "Phone / Helpline",
        required: true,
        aliases: ["phone", "mobile", "contact", "ফোন", "মোবাইল", "হেল্পলাইন"],
        exampleValue: "01811223344",
      },
      {
        key: "email",
        labelBn: "ইমেইল",
        labelEn: "Email",
        required: false,
        aliases: ["email", "e-mail", "ইমেইল"],
        exampleValue: "info@popularfeni.com",
      },
      {
        key: "logoText",
        labelBn: "লোগো টেক্সট / সংক্ষিপ্ত নাম",
        labelEn: "Logo Text / Short Name",
        required: true,
        aliases: ["logotext", "logo_text", "short_name", "লোগো টেক্সট", "সংক্ষিপ্ত নাম"],
        exampleValue: "Popular",
      },
      {
        key: "upazila",
        labelBn: "উপজেলা / এলাকা",
        labelEn: "Upazila / Area",
        required: false,
        aliases: ["upazila", "area", "উপজেলা", "এলাকা", "থানা"],
        exampleValue: "feni-sadar",
      },
      {
        key: "emergencyPhone",
        labelBn: "জরুরি হটলাইন",
        labelEn: "Emergency Phone",
        required: false,
        aliases: ["emergencyphone", "emergency_phone", "hotline", "জরুরি ফোন"],
        exampleValue: "01899112233",
      },
      {
        key: "workingHours",
        labelBn: "কার্যকাল / সেবা সময়",
        labelEn: "Working Hours",
        required: false,
        aliases: ["workinghours", "working_hours", "hours", "খোলা থাকার সময়"],
        exampleValue: "২৪ ঘণ্টা খোলা",
      },
    ],
  },
  donors: {
    type: "donors",
    titleBn: "রক্তদাতা নেটওয়ার্ক",
    titleEn: "Blood Donors",
    descBn: "স্বেচ্ছাসেবী রক্তদাতাদের নাম, রক্তের গ্রুপ, উপজেলা ও ফোন নম্বর",
    descEn: "Blood donors with blood group, upazila area and phone number",
    columns: [
      {
        key: "name",
        labelBn: "রক্তদাতার নাম",
        labelEn: "Donor Name",
        required: true,
        aliases: ["name", "donor_name", "নাম", "রক্তদাতার নাম"],
        exampleValue: "তানভীর আহমেদ",
      },
      {
        key: "bloodGroup",
        labelBn: "রক্তের গ্রুপ",
        labelEn: "Blood Group (A+, B+, O+, AB+, etc.)",
        required: true,
        aliases: ["bloodgroup", "blood_group", "group", "রক্তের গ্রুপ", "গ্রুপ"],
        exampleValue: "O+",
      },
      {
        key: "upazila",
        labelBn: "উপজেলা",
        labelEn: "Upazila (e.g. feni-sadar)",
        required: true,
        aliases: ["upazila", "thana", "area", "উপজেলা", "থানা", "এলাকা"],
        exampleValue: "feni-sadar",
      },
      {
        key: "phone",
        labelBn: "ফোন নম্বর",
        labelEn: "Phone Number",
        required: true,
        aliases: ["phone", "mobile", "contact", "ফোন", "মোবাইল"],
        exampleValue: "01812345678",
      },
      {
        key: "lastDonated",
        labelBn: "সর্বশেষ রক্তদানের তারিখ",
        labelEn: "Last Donation Date",
        required: false,
        aliases: ["lastdonated", "last_donated", "last_donation", "সর্বশেষ রক্তদান"],
        exampleValue: "২০২৬-০১-১৫",
      },
    ],
  },
  ambulances: {
    type: "ambulances",
    titleBn: "অ্যাম্বুলেন্স সার্ভিস",
    titleEn: "Ambulance Services",
    descBn: "জরুরি অ্যাম্বুলেন্স বহর, ধরন (ICU, AC, Non-AC, Freezer) ও অবস্থান",
    descEn: "Emergency ambulance fleet, type (ICU, AC, Non-AC, Freezer) and location",
    columns: [
      {
        key: "name",
        labelBn: "সার্ভিস / এজেন্সির নাম",
        labelEn: "Agency / Service Name",
        required: true,
        aliases: ["name", "agency_name", "ambulance_name", "নাম", "এজেন্সির নাম"],
        exampleValue: "ফেনী সেন্ট্রাল অ্যাম্বুলেন্স সার্ভিস",
      },
      {
        key: "type",
        labelBn: "অ্যাম্বুলেন্সের ধরন",
        labelEn: "Type (ICU / AC / Non-AC / Freezer)",
        required: true,
        aliases: ["type", "ambulance_type", "ধরন", "টাইপ"],
        exampleValue: "ICU",
      },
      {
        key: "location",
        labelBn: "অবস্থান / স্ট্যান্ড",
        labelEn: "Location / Station",
        required: true,
        aliases: ["location", "stand", "address", "অবস্থান", "স্ট্যান্ড", "ঠিকানা"],
        exampleValue: "সদর হাসপাতাল মোড়, ফেনী",
      },
      {
        key: "phone",
        labelBn: "ফোন নম্বর",
        labelEn: "Phone Number",
        required: true,
        aliases: ["phone", "mobile", "contact", "ফোন", "মোবাইল"],
        exampleValue: "01755112233",
      },
      {
        key: "availableHours",
        labelBn: "সার্ভিসের সময়",
        labelEn: "Available Hours",
        required: false,
        aliases: ["availablehours", "available_hours", "hours", "সময়"],
        exampleValue: "২৪ ঘণ্টা",
      },
    ],
  },
  hotlines: {
    type: "hotlines",
    titleBn: "জরুরি হটলাইন ও অক্সিজেন",
    titleEn: "Emergency Hotlines & Oxygen",
    descBn: "অক্সিজেন সেবা, ফায়ার সার্ভিস, পুলিশ ও হাসপাতালের সরাসরি হটলাইন",
    descEn: "Direct emergency contacts for Oxygen, Fire Service, Police & Hospitals",
    columns: [
      {
        key: "titleBn",
        labelBn: "সেবার নাম (বাংলা)",
        labelEn: "Title (Bengali)",
        required: true,
        aliases: ["titlebn", "title_bn", "name_bn", "নাম (বাংলা)", "সেবার নাম", "শিরোনাম"],
        exampleValue: "ফেনী অক্সিজেন ব্যাংক",
      },
      {
        key: "titleEn",
        labelBn: "সেবার নাম (ইংরেজি)",
        labelEn: "Title (English)",
        required: true,
        aliases: ["titleen", "title_en", "name_en", "title", "নাম (ইংরেজি)", "Name"],
        exampleValue: "Feni Oxygen Bank",
      },
      {
        key: "category",
        labelBn: "ক্যাটাগরি",
        labelEn: "Category (hospital/oxygen/fire/police/blood_bank)",
        required: true,
        aliases: ["category", "type", "ক্যাটাগরি", "ধরন"],
        exampleValue: "oxygen",
      },
      {
        key: "phone",
        labelBn: "হটলাইন নম্বর",
        labelEn: "Hotline Phone",
        required: true,
        aliases: ["phone", "hotline", "mobile", "ফোন", "হটলাইন"],
        exampleValue: "01833445566",
      },
      {
        key: "descriptionBn",
        labelBn: "বিবরণ (বাংলা)",
        labelEn: "Description (Bengali)",
        required: false,
        aliases: ["descriptionbn", "description_bn", "desc_bn", "বিবরণ"],
        exampleValue: "ফেনী জেলার যেকোনো স্থানে ২৪ ঘণ্টা ফ্রি অক্সিজেন সিলিন্ডার ডেলিভারি",
      },
      {
        key: "descriptionEn",
        labelBn: "বিবরণ (ইংরেজি)",
        labelEn: "Description (English)",
        required: false,
        aliases: ["descriptionen", "description_en", "desc_en", "description"],
        exampleValue: "24/7 free home delivery of oxygen cylinders across Feni district",
      },
    ],
  },
};
