export const HOME_CARE_ENGLISH_INTROS: Record<string, string[]> = {
  "home-sample-collection-and-nursing-service-in-feni": [
    "In contemporary clinical medicine, home healthcare and mobile phlebotomy represent vital pillars of compassionate, patient-centered care. For individuals suffering from geriatric frailty, post-stroke hemiplegia, debilitating osteoarthritis, or major surgical recovery, traveling to diagnostic laboratories or waiting in crowded outpatient queues poses immense physical distress and clinical hazards. The physical exertion of negotiating stairs, vehicular vibration during transit, and prolonged immobility in waiting rooms can destabilize blood pressure and vital signs. Furthermore, exposure to high-density hospital outpatient environments significantly escalates the risk of nosocomial and respiratory infections among vulnerable, immunocompromised elderly individuals. To resolve these challenges, mobile phlebotomy and on-call home clinical nursing services in Feni Sadar provide safe, hospital-grade care directly inside the home.",
    "During in-home pathology testing, strict cold-chain preservation and aseptic venipuncture are paramount. For routine diagnostic investigations—such as fasting blood sugar (FBS), glycated hemoglobin (HbA1c), serum creatinine, complete blood count (CBC), and lipid panels—certified phlebotomists employ single-use vacuum-sealed vacutainer tubes. If whole blood specimens are subjected to ambient tropical temperatures during transit, in-vitro cellular hemolysis rapidly elevates potassium levels and triggers enzymatic glucose degradation. Accredited partner diagnostic centers in Feni enforce strict specimen preservation using insulated cold-chain thermal cooler bags regulated between 2°C and 8°C, guaranteeing analytical accuracy identical to on-site hospital collection. Diagnostic reports are digitized immediately and delivered as secure PDFs directly to patients and family members via WhatsApp or email.",
    "Equally essential for bedridden and immobilized patients is skilled, certified nursing intervention. Indwelling urinary Foley catheters require aseptic exchange every 3 to 4 weeks; clumsy attempts by unqualified personnel frequently precipitate traumatic urethral injury, strictures, or life-threatening Catheter-Associated Urinary Tract Infections (CAUTI). Similarly, establishing intravenous cannula access, administering saline or antibiotic infusions, dressing post-operative incisions or chronic diabetic foot ulcers, inserting nasogastric (NG) feeding tubes, and managing portable suctioning for tracheostomy patients demand strict aseptic technique and clinical certification. Families must rely on government-registered diploma nurses rather than untrained pharmacy assistants to avert severe septic complications.",
    "With a large proportion of Feni's working population residing abroad in the Middle East, Europe, and North America, ensuring the continuous health surveillance of aging parents left behind is an ongoing concern. Overseas expatriate sponsors can schedule on-call nursing visits and diagnostic collections through official partner hospital [Al-Aqsa Hospital Ltd](/blog/feni-icu-ccu-nicu-bed-charges-and-facilities-guide), as well as partner diagnostic centers Pacific Health Care, Life Care, Imperial Neurocare, and Feni Max. Patients and families can also consult our [Full Body Health Checkup Guide](/blog/full-body-health-checkup-packages-in-feni), [Feni Diabetic Hospital Guide](/blog/feni-diabetic-hospital-guide), [Top Medicine Specialists](/blog/best-medicine-doctors-in-feni), and [24/7 Ambulance Fleet](/blog/feni-ambulance-and-oxygen-service-guide). Registered Health Club members receive guaranteed 10-30% discounts across home sample pickup, clinical nursing visits, and laboratory investigations at verified partner facilities in Feni Sadar.",
  ],
};

export const HOME_CARE_ENGLISH_HIGHLIGHTS: Record<string, string[]> = {
  "home-sample-collection-and-nursing-service-in-feni": [
    "Doorstep Blood & Specimen Collection: Sterile phlebotomy utilizing vacuum-sealed vacutainers for diabetic, renal, or bedridden patients directly at home, eliminating stressful travel.",
    "Cold-Chain Specimen Preservation: Mandatory transport inside insulated thermal coolers (2°C-8°C) with ice-gel packs prevents in-vitro hemolysis and ensures hospital-grade accuracy.",
    "Certified On-Call Clinical Nursing: Licensed diploma/BSc nurses available for sterile Foley urinary catheterization, IV cannula & saline infusion, and vital sign monitoring.",
    "Diabetic Foot & Surgical Wound Care: Autoclaved surgical instruments and antiseptic dressing protocols prevent infection and promote healthy tissue granulation without clinic lines.",
    "NG Tube & Tracheostomy Airway Care: Trained clinical protocols for nasogastric feeding tube placement and portable airway suctioning for immobilized stroke patients.",
    "Overseas Expatriate Coordination: Non-resident Bangladeshi children can remotely schedule, monitor, and finance comprehensive home diagnostics and nursing care for elderly parents.",
    "Guaranteed 10-30% Health Club Savings: Members receive 10-30% discounts on sample pickup charges, nursing call-out fees, and laboratory tests at accredited partner facilities.",
  ],
};
